### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by nijinekoyo**
Add Chinese translation for iTorrent v2

I edited the `Localizable.xcstrings` file as JSON format. If there are any errors, please let me know.

### CODE REVIEW

**Comment by XITRIX** [comment]
Thanks for contribution! 
Currently I have no possibility to validate it with xCode, but I'll respond you as soon as I will be able to do that.

**Comment by XITRIX** [comment]
I checked, looks fine, thanks a lot for contribution!

**Comment by nijinekoyo** [comment]
okk
By the way, can you notify me when the translation files need to be updated?

**Comment by nijinekoyo** [comment]
It’s a bit difficult to tell if an update is needed by looking at the commit. If you can tell me directly, I can submit the update faster.

**Comment by XITRIX** [comment]
Sorry, I did not get about which update you are talking about? I've checked your translation and looks fine to me
Screenshot 2024-09-08 at 23 01 15

**Comment by nijinekoyo** [comment]
Sorry, there may be some misunderstanding in my expression.
I mean, if there is a need to update the translation, you can notify me directly so that I know it needs to be updated.
>抱歉，我的表达可能有些误会
我的意思是，如果有需要更新翻译，可以直接通知我一下，方便我知道需要更新了

**Comment by XITRIX** [comment]
Ah, ok, thanks, from my point of view it looks nice (of course I have no idea how good the translation really is, because I do not understand it :D )
If you want, I could build an ipa file for you, so you can install it and doublecheck you translation in the app, or you could just wait till next release and PR changes later if you'll find something to change

**Comment by nijinekoyo** [comment]
Oh, sorry, I don't know if my English made you misunderstand, could you please use machine translation to translate the following sentence from Chinese into your native language?
>我希望你可以在需要更新翻译的时候通知我一下，也就是说，如果`Localizable.xcstrings`需要更新了，就告诉我一下

**Comment by XITRIX** [comment]
Thanks, yes, I got it, for now it's all good, if I'll need any update, I'll ping you

**Pull request merged**
